---
title: "12-sankey-diag"
author: "Fleur.Lecarpentier"
date: "11 novembre 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(plotly)
```

#### NEW: Sandkey

```{r}

  load(file = "./datasets/Sankey.RData", verbose = T)

  # create list of labels
  label.list = factor(unique(c(sankey.df$label.source, sankey.df$label.target)))

 plot_ly(sankey.df, type = "sankey", orientation = "h",  
         ##nodes
         node = list(label = label.list,
                     color = rainbow(length(label.list)),
                     pad = 15,
                     thickness = 15,
                     line = list(color = "black",
                                width = 0.5)),
                   ## link
                     link = list(source = ~source,
                                 target = ~target,
                                 value =  ~value)) %>% 
       layout( title = "SanKey Example",
                             font = list(size = 10),
                             margin = list(t = 20),
                             xaxis = list(showgrid = F, zeroline = F),
                             yaxis = list(showgrid = F, zeroline = F)
                     )


```